version: "3.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /config/code-server/data:/config
      - /config:/config/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vs.entrypoints=http"
      - "traefik.http.routers.vs.rule=Host(`vs.speedbird.house`)"
      - "traefik.http.middlewares.vs-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vs.middlewares=vs-https-redirect"
      - "traefik.http.routers.vs-secure.entrypoints=https"
      - "traefik.http.routers.vs-secure.rule=Host(`vs.speedbird.house`)"
      - "traefik.http.routers.vs-secure.tls=true"
      - "traefik.http.routers.vs-secure.service=vs"
      - "traefik.http.services.vs.loadbalancer.server.port=8443"
      - "traefik.docker.network=proxy"