version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'UTC'
    networks:
      - default_smb
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /A380/share:/A380:z
    command: '-s "A380;/A380;yes;no;no;ninja;ninja" -u "ninja;password" -p'

networks:
  default_smb: